title: My Page
baseURL: 'https://eecczz.github.io/'
languages:
  en:
    languageName: "English"
    weight: 1
    contentDir: "content/en"
    menu: 
      main: 
        - identifier: "home"
          name: "Home"
          url: "/"
          weight: 10
    
  ko:
    languageName: "한국어"
    weight: 2
    contentDir: "content/ko"
    menu: 
      main: 
        - identifier: "home"
          name: "홈"
          url: "/"
          weight: 10
params:
  fontawesome: true