# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # 상위 메뉴 항목
  - name: "홈"  # i18n 파일에서 'menu.home' 키를 사용
    url: "/"
    weight: 10

  - name: "소개"
    url: "/about/"
    weight: 20

  - name: "게임프로젝트"
    url: "/game-projects/"
    weight: 30

  - name: "웹프로젝트"
    url: "/web-projects/"
    weight: 40

  - name: "연락처"
    url: "/contact/"
    weight: 50

  # 하위 메뉴 항목 (parent 속성을 사용)
  - name: "메인"
    url: "/"
    parent: "홈"
    weight: 11

  - name: "황선우"
    url: "/about/"
    parent: "소개"
    weight: 21

  - name: "검술대련"
    url: "/game-projects/swordplay/"
    parent: "게임프로젝트"
    weight: 31

  - name: "소울라이크 게임"
    url: "/game-projects/soulslike-game/"
    parent: "게임프로젝트"
    weight: 32

  - name: "유튜브클론웹"
    url: "/web-projects/youtube-clone/"
    parent: "웹프로젝트"
    weight: 41

  - name: "쇼핑몰"
    url: "/web-projects/shopping-mall/"
    parent: "웹프로젝트"
    weight: 42

  - name: "프로젝트 참여하기"
    url: "/contact/"
    parent: "연락처"
    weight: 51
