# Navigation Links

main:
  - name: "Home"
    url: "/"
    weight: 10

  - name: "About"
    url: "/about/"
    weight: 20

  - name: "Toy Projects"
    url: "/toy-projects/"
    weight: 30

  - name: "Major & Competition Projects"
    url: "/contest-projects/"
    weight: 40

  - name: "Contact"
    url: "/contact/"
    weight: 50

  - name: "Main"
    url: "/"
    parent: "Home"
    weight: 11

  - name: "Hwang Seon-woo"
    url: "/author/admin/"
    parent: "About"
    weight: 21

  - name: "Swordplay"
    url: "/toy-projects/swordplay/"
    parent: "Toy Projects"
    weight: 31

  - name: "MetaXR"
    url: "/toy-projects/metaxr-project/"
    parent: "Toy Projects"
    weight: 32

  - name: "3D Horror Game"
    url: "/toy-projects/my3dhorrorgame/"
    parent: "Toy Projects"
    weight: 33

  - name: "Shopping Mall"
    url: "/toy-projects/shopping-mall/"
    parent: "Toy Projects"
    weight: 34

  - name: "YouTube Remake"
    url: "/toy-projects/youtube-clone/"
    parent: "Toy Projects"
    weight: 35

  - name: "Job API"
    url: "/toy-projects/job-api/"
    parent: "Toy Projects"
    weight: 37

  - name: "My Movie Web"
    url: "/toy-projects/my-movie-web/"
    parent: "Toy Projects"
    weight: 38

  - name: "ClipAnalyst"
    url: "/toy-projects/sports-analyzer/"
    parent: "Toy Projects"
    weight: 39

  - name: "Restaurant ReAct Agent"
    url: "/toy-projects/restaurant-agent/"
    parent: "Toy Projects"
    weight: 40

  - name: "SpeakUp"
    url: "/contest-projects/speech-coach/"
    parent: "Major & Competition Projects"
    weight: 41

  - name: "Jeonbuk Voice Chatbot"
    url: "/contest-projects/jeonbuk-chatbot/"
    parent: "Major & Competition Projects"
    weight: 42

  - name: "Soulslike Game"
    url: "/contest-projects/soulslike-game/"
    parent: "Major & Competition Projects"
    weight: 43

  - name: "Gone"
    url: "/contest-projects/gone/"
    parent: "Major & Competition Projects"
    weight: 44

  - name: "TRIPICK"
    url: "/contest-projects/tripick/"
    parent: "Major & Competition Projects"
    weight: 45

  - name: "Contact"
    url: "/contact/"
    parent: "Contact"
    weight: 51

  - name: "GitHub"
    url: "https://github.com/eecczz?tab=repositories"
    parent: "Contact"
    weight: 52
