# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # 상위 메뉴 항목
  - name: "home"  # i18n 파일에서 'menu.home' 키를 사용
    url: "/"
    weight: 10

  - name: "about"
    url: "/about/"
    weight: 20

  - name: "game projects"
    url: "/game-projects/"
    weight: 30

  - name: "web projects"
    url: "/web-projects/"
    weight: 40

  - name: "contact"
    url: "/contact/"
    weight: 50

  # 하위 메뉴 항목 (parent 속성을 사용)
  - name: "main"
    url: "/"
    parent: "home"
    weight: 11

  - name: "Hwang-seonwoo"
    url: "/about/"
    parent: "about"
    weight: 21

  - name: "swordplay"
    url: "/game-projects/swordplay/"
    parent: "game projects"
    weight: 31

  - name: "Gone"
    url: "/game-projects/gone/"
    parent: "game projects"
    weight: 32

  - name: "youtube-clone"
    url: "/web-projects/youtube-clone/"
    parent: "web projects"
    weight: 41

  - name: "join project"
    url: "/contact/"
    parent: "contact"
    weight: 51

  - name: "see more project"
    url: 'https://github.com/eecczz?tab=repositories'
    parent: "contact"
    weight: 52