# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # 상위 메뉴 항목
  - name: "home"  # i18n 파일에서 'menu.home' 키를 사용
    url: "/"
    weight: 10

  - name: "about"
    url: "/about/"
    weight: 20

  - name: "personal projects"
    weight: 30

  - name: "team projects"
    weight: 40

  - name: "contact"
    url: "/contact/"
    weight: 50

  # 하위 메뉴 항목 (parent 속성을 사용)
  - name: "main"
    url: "/"
    parent: "home"
    weight: 11

  - name: "Hwang-seonwoo"
    url: "/authors/이경수"
    parent: "about"
    weight: 21

  - name: "swordplay"
    url: "/swordplay/"
    parent: "personal projects"
    weight: 31

  - name: "youtube-clone"
    url: "/youtube-clone/"
    parent: "personal projects"
    weight: 32

  - name: "see team projects"
    url: "/team-project/"
    parent: "team projects"
    weight: 41

  - name: "join project"
    url: "/contact/"
    parent: "contact"
    weight: 51

  - name: "see more project"
    url: 'https://github.com/eecczz?tab=repositories'
    parent: "contact"
    weight: 52