# Navigation Links

main:
  - name: "홈"
    url: "/"
    weight: 10

  - name: "소개"
    url: "/about/"
    weight: 20

  - name: "토이 프로젝트"
    url: "/toy-projects/"
    weight: 30

  - name: "팀·수상·현장 프로젝트"
    url: "/contest-projects/"
    weight: 40

  - name: "연락처"
    url: "/contact/"
    weight: 50

  - name: "메인"
    url: "/"
    parent: "홈"
    weight: 11

  - name: "황선우"
    url: "/author/황선우/"
    parent: "소개"
    weight: 21

  - name: "검술대련"
    url: "/toy-projects/swordplay/"
    parent: "토이 프로젝트"
    weight: 31

  - name: "MetaXR"
    url: "/toy-projects/metaxr-project/"
    parent: "토이 프로젝트"
    weight: 32

  - name: "3D Horror Game"
    url: "/toy-projects/my3dhorrorgame/"
    parent: "토이 프로젝트"
    weight: 33

  - name: "쇼핑몰 프로젝트"
    url: "/toy-projects/shopping-mall/"
    parent: "토이 프로젝트"
    weight: 34

  - name: "유튜브 클론"
    url: "/toy-projects/youtube-clone/"
    parent: "토이 프로젝트"
    weight: 35

  - name: "Job API"
    url: "/toy-projects/job-api/"
    parent: "토이 프로젝트"
    weight: 37

  - name: "My Movie Web"
    url: "/toy-projects/my-movie-web/"
    parent: "토이 프로젝트"
    weight: 38

  - name: "ClipAnalyst"
    url: "/toy-projects/sports-analyzer/"
    parent: "토이 프로젝트"
    weight: 39

  - name: "맛집 ReAct Agent"
    url: "/toy-projects/restaurant-agent/"
    parent: "토이 프로젝트"
    weight: 40

  - name: "SpeakUp"
    url: "/contest-projects/speech-coach/"
    parent: "팀·수상·현장 프로젝트"
    weight: 41

  - name: "Smart CCTV 낙상 감지"
    url: "/contest-projects/smartcctv-fall/"
    parent: "팀·수상·현장 프로젝트"
    weight: 39

  - name: "Smart CCTV 차종 분류"
    url: "/contest-projects/smartcctv-car/"
    parent: "팀·수상·현장 프로젝트"
    weight: 40

  - name: "대도민 음성 챗봇"
    url: "/contest-projects/jeonbuk-chatbot/"
    parent: "팀·수상·현장 프로젝트"
    weight: 42

  - name: "소울라이크 게임"
    url: "/contest-projects/soulslike-game/"
    parent: "팀·수상·현장 프로젝트"
    weight: 43

  - name: "Gone"
    url: "/contest-projects/gone/"
    parent: "팀·수상·현장 프로젝트"
    weight: 44

  - name: "TRIPICK"
    url: "/contest-projects/tripick/"
    parent: "팀·수상·현장 프로젝트"
    weight: 45

  - name: "문의"
    url: "/contact/"
    parent: "연락처"
    weight: 51

  - name: "GitHub"
    url: "https://github.com/eecczz?tab=repositories"
    parent: "연락처"
    weight: 52
